### PR TITLE
Added support for ODT export.

### PR DESCRIPTION
**Pull request by LarsGit223**
Hello Satoshi,

I implemented ODT support for your exttab3 plugin. Please merge if you like it.
P.S.: It requires the current master version of the ODT plugin to work.

Best Regards,
Lars

### CODE REVIEW

**Comment by ssahara** [comment]
Hello @LarsGit223 ,
The PR is further working in progress at [odt branch](https://github.com/ssahara/dw-plugin-exttable/commits/odt)

**Comment by LarsGit223** [comment]
Hi @ssahara,
Ok, thanks for the info. Do you expect me to do anything? Is any assistance required?
Best Regards,
Lars

**Comment by ssahara** [comment]
Hello @LarsGit223 
New release 2015-06-11 that supports ODT export now available. It just wonder that `getODTProperties()` read odt.css but not style.css file ?

**Comment by LarsGit223** [comment]
Hi @ssahara,

this is the behaviour which has beend adopted from the **dw2pdf** plugin:

`odt.css` will be imported, if not present `print.css` will be used.
**Exception:** if a plugin is listed in the config option `usestyles` then for that plugin `screen.css` and `style.css`will be used.

**Pull request merged**
